name = "ChannelflowWrapper"
uuid = "96086318-f2c4-4a08-8036-25bfacd5eac3"
authors = ["Eben Quenneville <tonehaven@outlook.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Channelflow_jll = "3f71b17c-0b5c-5f71-8ab7-7b799a58f30d"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
Channelflow_jll = "~1"
DelimitedFiles = "1.9.1"
julia = "1.11"

[sources]
Channelflow_jll = {url = "https://github.com/TonehavenE/Channelflow_jll.jl"}

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
